version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "StarForgeWorker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
