name: 'Submodule - Publish'

on:
  workflow_call:

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout project sources'
        uses: actions/checkout@v4
